version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  fpm:
    container_name: fpm
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - ./:/var/www/
    links:
      - mysql
    networks:
      - app-tier

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    links:
      - fpm
      - mysql
    networks:
      - app-tier
    ports:
      - "127.0.0.1:82:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./:/var/www/

  mysql:
    image: mysql:8.0
    container_name: mysql
    build:
      context: .
    restart: always
    networks:
      - app-tier
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_DATABASE: app_storage
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: 15754959
      MYSQL_PASSWORD: weFLL1W45KK956nZunEjZRxh3g1E75ks1xc
    volumes:
      - ./docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.1
    container_name: phpmyadmin
    restart: always
    networks:
      - app-tier
    ports:
      - "127.0.0.1:89:80"
    environment:
      PMA_HOST: mysql




